---
# tasks file for ansible-role-rsyslog-client
#
- name: install rsyslog
  yum: name=rsyslog state=installed
  when: central_log_shipper or central_log_listener

- name: "template in rsyslog config if a log shipper or listener"
  template: src=central_syslog.conf.j2 dest={{ syslog_conf_path }}/{{ central_conf_file }} owner=root group=root mode=0644 backup=yes
  notify: Restart rsyslog
  when: central_log_shipper or central_log_listener

- name: "Create location of remote logs"
  file: "path={{ central_logs_directory }} state=directory owner=root group=root mode=0755"
  when: central_log_listener

- name: Add logrotate for remote logs
  template: src=remote_logrotate.j2 dest=/etc/logrotate.d/remote_logrotate owner=root group=root mode=0644
  when: central_log_listener

